# Generated by Django 2.1.4 on 2019-10-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='andar',
            field=models.CharField(default='1E', max_length=300),
            preserve_default=False,
        ),
    ]
