# Generated by Django 2.2.5 on 2019-09-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoGranel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('price', models.FloatField()),
                ('image', models.ImageField(height_field=500, upload_to='static/catalog/img', width_field=450)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('size', models.CharField(choices=[('0.50kg', '0.50kg'), ('1.00kg', '1.00kg'), ('1.50kg', '1.50kg')], default='0.50kg', max_length=10)),
            ],
        ),
    ]
