# Generated by Django 2.2.5 on 2019-09-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtogranel',
            name='image',
            field=models.ImageField(height_field='500', upload_to='static/catalog/img', width_field='450'),
        ),
    ]
