# Generated by Django 2.2.5 on 2019-09-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_delete_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtogranel',
            name='product_type',
            field=models.CharField(choices=[('Granel', 'Granel'), ('Individuais', 'Individuais')], default='Granel', max_length=50),
            preserve_default=False,
        ),
    ]
