# Generated by Django 2.1.4 on 2019-09-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_produtogranel_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtogranel',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
